/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expense.tracker;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author hrish
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Money.setVisible(false);
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
    public void username(String str1){
        txt_label.setText(str1); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Money = new javax.swing.JPanel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new necesario.RSMaterialButtonCircle();
        jButton5 = new javax.swing.JButton();
        txt_label = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        rSMaterialButtonCircle4 = new necesario.RSMaterialButtonCircle();
        jLabel2 = new javax.swing.JLabel();
        amt = new app.bolivia.swing.JCTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();
        rSMaterialButtonCircle5 = new necesario.RSMaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Money.setBackground(new java.awt.Color(22, 33, 50));
        Money.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white));
        Money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoneyMouseClicked(evt);
            }
        });
        Money.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(106, 11, 35));
        rSMaterialButtonCircle1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        rSMaterialButtonCircle1.setText("Expense");
        rSMaterialButtonCircle1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        Money.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 310, 60));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(30, 56, 4));
        rSMaterialButtonCircle2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        rSMaterialButtonCircle2.setText("Income");
        rSMaterialButtonCircle2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        Money.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 310, 60));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonCircle3.setText("Cancel");
        rSMaterialButtonCircle3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        Money.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 320, 60));

        getContentPane().add(Money, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 400));

        jButton5.setText("View monthly");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 40));

        txt_label.setForeground(new java.awt.Color(233, 221, 235));
        getContentPane().add(txt_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        jButton6.setText("View date wise");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, 40));

        jButton7.setText("View category");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 100, 40));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle4.setText("x");
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        jLabel2.setText("Amt spent:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        amt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null));
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Uid", "S.no", "Category", "Vendor", "Amount", "paid by", "Expense/Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColorBackgoundHead(new java.awt.Color(120, 120, 176));
        table.setFuenteFilas(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table.setFuenteHead(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 780, 370));

        rSMaterialButtonCircle5.setText("rSMaterialButtonCircle5");
        rSMaterialButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle5ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        jPanel1.setBackground(new java.awt.Color(233, 221, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("View today");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 90, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hrish\\OneDrive\\Pictures\\expens tracker\\icons\\pixlr-bg-result.png")); // NOI18N
        jButton2.setText("Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 160, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expense/tracker/account_24px.png"))); // NOI18N
        jButton3.setText("Reports-Category");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 170, 50));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hrish\\OneDrive\\Pictures\\expens tracker\\icons\\icons\\adminIcons\\icons8_Exit_26px.png")); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 130, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hrish\\OneDrive\\Pictures\\expens tracker\\icons\\home_24px.png")); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Money.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        Money.setVisible(false);
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        ExpensePage ep = new ExpensePage();
        String str1= txt_label.getText();
        ep.username(str1);
        ep.setVisible(true);
      
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void MoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoneyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyMouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
         IncomePage ep = new IncomePage();
        String str1= txt_label.getText();
        ep.username(str1);
        ep.setVisible(true);
        
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        View v= new View();
        String str1 = txt_label.getText();
        v.username(str1);
        v.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Viewduration vd= new Viewduration();
        String str1 = txt_label.getText();
        vd.username(str1);
        vd.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ViewCat vc = new ViewCat();
        String str1 = txt_label.getText();
        vc.username(str1);
        vc.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try{
            
            
            javax.swing.table.DefaultTableModel dtm=
                    (javax.swing.table.DefaultTableModel)table.getModel();
            int rc=dtm.getRowCount();
            while(rc--!=0){
                dtm.removeRow(0);
            }
            java.time.LocalDate cd= java.time.LocalDate.now();
            java.time.LocalDate bd = cd.minusDays(0);
            int sno=0;
            
                Connection con = DBConnection.getConnection();
              Statement s = con.createStatement();
              String str1 = txt_label.getText();
            
              ResultSet rs= s.executeQuery("select ID from users where name='"+str1+"'");
              rs.next();
              String sd = rs.getString(1);
              int id=Integer.parseInt(sd);
              int total=0;
              rs = s.executeQuery("select cat,amt,py,vendor,type,idm from money where day<='"+cd+"' and day>='"+bd+"' and Pid='"+id+"'");
              while(rs.next()){
                String cat,paidby,vendor,type;
                int amt;
                int idm;
                Date d;
                cat=rs.getString("cat");
                amt=rs.getInt("amt");
                paidby=rs.getString("py");
                vendor=rs.getString("vendor");
                type=rs.getString("type");
                idm=rs.getInt("idm");
                Object o[]={idm,++sno,cat,vendor,amt,paidby,type};
                dtm.addRow(o);
                if("Expense".equals(type)){
                    total+=total+amt;
                }
                
              }
              
              String am=Integer.toString(total);
              amt.setText(am);
            
             
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
       
                               
         
       
                               
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
           
             java.time.LocalDate cd= java.time.LocalDate.now();
             java.time.LocalDate bd = cd.minusDays(20);
       
              String str1 = txt_label.getText();
              Connection con = DBConnection.getConnection();
              Statement s = con.createStatement();
              ResultSet rs= s.executeQuery("select ID from users where name='"+str1+"'");
              rs.next();
              int i = 0;
              int k=0;
               rs = s.executeQuery("select count(cate) from category");
              while(rs.next()){
                  i=rs.getInt(1);
                  
              }
              String[] ca= new String[i];
              int[] am=new int[i];
               rs = s.executeQuery("select * from category");
              while(rs.next()){
                  String cat;
                  cat=rs.getString("cate");
                  ca[k]=cat;
                  k=k+1;
                  
              }
              rs= s.executeQuery("select ID from users where name='"+str1+"'");
              rs.next();
              String sd = rs.getString(1);
              int id=Integer.parseInt(sd);
                int total;
                int j;
                System.out.println(ca[3]);
                for(j=0;j<i;j++){
                    total=0;
                    String cat;
                    cat=ca[j];
                    rs = s.executeQuery("select amt from money where day<='"+cd+"'and day>='"+bd+"' and cat='"+cat+"' and Pid='"+id+"' ");
                while(rs.next()){
                int amt;
                amt=rs.getInt("amt");
                total+=amt;
               
                
                }
                am[j]=total;
                } 
              
                
      
                      
       DefaultPieDataset pieDataset = new DefaultPieDataset();
       for(j=0;j<i;j++){
           pieDataset.setValue(ca[j],am[j]);
       }
       JFreeChart chart = ChartFactory.createPieChart("Category wise", pieDataset,true,true,true);
       PiePlot p=(PiePlot)chart.getPlot();
       //p.setForegroundAlpha(TOP_ALIGNMENT);
       ChartFrame frame = new ChartFrame("Pie Chart",chart);
       frame.setVisible(true);
       frame.setSize(500,500);
       
       
       
       }
       catch(Exception e){
           System.out.println(e);
       }
        
        
        
        
        
        
        
        
      
     
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rSMaterialButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(this,"Logged out successfully");
        LoginPage lp= new LoginPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Money;
    private app.bolivia.swing.JCTextField amt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle5;
    private rojeru_san.complementos.RSTableMetro table;
    private javax.swing.JLabel txt_label;
    // End of variables declaration//GEN-END:variables
}
